# Generated by Django 3.2.8 on 2021-10-21 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Category ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('datecreated', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('url', models.URLField(default='Enter the URL here', verbose_name='Playlist URL')),
                ('channelname', models.CharField(blank=True, max_length=100, verbose_name='Channel Name')),
                ('datecreated', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_category', to='back.categories', verbose_name='Category')),
            ],
        ),
    ]
